Split сonfig web|console.php to small files
yiisoft/yii-base-web pull request #20
Opened 2018-05-11 10:11 UTC by exileed

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | yes
| Tests pass?   | yes
| Fixed issues  | https://github.com/yiisoft/yii2-app/issues/17

2018-05-11 12:42 UTC, marcelodeandrade requested changes
Following [PSR-2](https://www.php-fig.org/psr/psr-2/#22-files), insert a blank line at end of files.

2018-05-17 16:15 UTC, marcelodeandrade approved these changes

2018-05-18 11:44 UTC, schmunk42 requested changes
See discussion in https://github.com/yiisoft/yii2-app/issues/17

2018-05-18 12:14 UTC, marcelodeandrade approved these changes

2018-08-25 11:23 UTC, hiqsol commented
Sorry, closing this PR.
This package is rewritten substantially.
Please redo your PR if it is still actual.

2018-08-25 11:23 UTC, closed without merging