updated views and widgets to not require asset packages
yiisoft/yii-base-web pull request #59
Opened 2018-11-30 15:04 UTC by schmunk42

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | yes
| Tests pass?   | ?

Related https://github.com/yiisoft/yii-console/issues/12#issuecomment-443163191

I've just uncommented the Bootstrap widgets as an example.

The Alert is currently outputting JSON content, this is an example for content that could be wrapped in a JS variable and function as initial "Server Side Rendered" data. This should be easily usable with native JS, jQuery, Vue or any other JS-lib.

Contact and Login are currently not working, but I think that's a separate issue atm.

2018-11-30 15:06 UTC, schmunk42 commented
Looks like this atm:
![bildschirmfoto von 2018-11-30 16-05-19](https://user-images.githubusercontent.com/649031/49296962-d5ece780-f4b9-11e8-8177-c80ceaa2e11d.png)
![bildschirmfoto von 2018-11-30 16-05-28](https://user-images.githubusercontent.com/649031/49296960-d5ece780-f4b9-11e8-9588-77042fcf1567.png)

For sure we can supply some basic CSS also in a later step.

2018-12-01 21:34 UTC, samdark requested changes

2018-12-01 21:34 UTC, samdark commented on src/controllers/SiteController.php
> +        $this->app->getSession()->addFlash('info', 'Hello World!');
Maybe it's better to display something like "Hello, it is flash info message."?

2018-12-01 21:34 UTC, samdark commented on src/views/layouts/main.php
> +    <?php /* example for bootstrap 4 navbar, if yiisoft/yii-bootstrap4 is installed
Not sure we need that...

2018-12-01 21:34 UTC, samdark commented on src/views/site/index.php
> +                    This is the Index page. You may modify the following file to customize its content:
Good idea to have it instead of gibberish...

2018-12-01 21:34 UTC, samdark commented on src/views/site/index.php
> +                <code><?= __FILE__ ?></code>
Should be HTML-encoded.

2018-12-01 21:34 UTC, samdark commented on src/widgets/Alert.php
> +            echo "<data id='{$this->id}'>";
Widget should not echo. It should return.

2018-12-03 17:32 UTC, merged

2018-12-03 17:33 UTC, schmunk42 commented
Sorry I accidentally merged this, while pushing to `master` (used wrong remote).
Comments should be fixed, let me know if there are other issues.

2018-12-03 17:37 UTC, schmunk42 commented
See https://github.com/yiisoft/yii-base-web/commit/8013f2f60903835ae59a13b8985b694f616e7227